apiVersion: v1
kind: ConfigMap
metadata:
  name: persist-contacts-config
  namespace: default
  labels:
    app: data-persistence
  annotations:
    description: "Configuração do microsserviço de Persistência de Dados."
data:
  RABBITMQ_HOST: "rabbitmq-service"
  RABBITMQ_PORT: "5672"
  RABBITMQ_USER: "guest"
  RABBITMQ_PASSWORD: "guest"
  APP_SETTING: "DataPersistenceSpecificConfig"
  SQLSERVER_CONNECTION_STRING: "Server=mssql-service,1433;Database=Contacts;User Id=sa;Password=NovaSenhaForte123;TrustServerCertificate=True;Encrypt=False;"