apiVersion: v1
kind: Service
metadata:
  name: persist-contacts-service
  labels:
    app: persist-contacts
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31407
  selector:
    app: persist-contacts
