apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
spec:
  type: NodePort
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      protocol: TCP
      port: 5672
      targetPort: 5672
      nodePort: 30000   # Porta externa para conexão de mensagens
    - name: management
      protocol: TCP
      port: 15672
      targetPort: 15672
      nodePort: 30001   # Porta externa para o painel do RabbitMQ
