apiVersion: v1
kind: Service
metadata:
  name: create-contact-service
  labels:
    app: create-contact
spec:
  type: NodePort
  selector:
    app: create-contact
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32623
