name: CI Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restaurar dependências
        run: dotnet restore

      - name: Compilar todos os projetos
        run: dotnet build --configuration Debug --no-restore

  unit_tests:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restaurar dependências
        run: dotnet restore

      - name: Compilar testes unitários
        run: dotnet build --configuration Debug --no-restore

      - name: Executar testes unitários
        run: dotnet test --configuration Debug --no-build --verbosity normal

  integration_tests:
    runs-on: ubuntu-latest
    needs: build

    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          SA_PASSWORD: "NovaSenhaForte123"
          ACCEPT_EULA: "Y"
        ports:
          - 1433:1433
        options: >-
          --memory=4g
          --shm-size=1g

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restaurar dependências
        run: dotnet restore

      - name: Esperar SQL Server estar pronto manualmente
        run: |
          echo "Aguardando SQL Server iniciar..."
          sleep 30
          for i in {1..30}; do
            if docker logs $(docker ps -q --filter "ancestor=mcr.microsoft.com/mssql/server:2022-latest") 2>&1 | grep -q "SQL Server is now ready for client connections"; then
              echo "SQL Server está pronto!"
              exit 0
            fi
            echo "Aguardando SQL Server... Tentativa $i de 30"
            sleep 5
          done
          echo "Erro: SQL Server não inicializou a tempo"
          exit 1

      - name: Criar banco de dados
        run: |
          /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P NovaSenhaForte123 -Q "CREATE DATABASE Contacts;"

      - name: Executar testes de integração
        env:
          ConnectionStrings__ConexaoPadrao: "Server=localhost,1433; Database=Contacts; User Id=sa; Password=NovaSenhaForte123; TrustServerCertificate=True"
        run: dotnet test --configuration Debug --no-build --verbosity normal

  docker_build_push:
    runs-on: ubuntu-latest
    needs: [unit_tests, integration_tests]

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Autenticar no Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Construir e enviar imagens Docker
        run: |
          for service in Contatos Consulta Atualizacao Exclusao Persistencia; do
            docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/techchallenge-${service,,}:latest -f $service/Dockerfile .
            docker push ${{ secrets.DOCKER_HUB_USERNAME }}/techchallenge-${service,,}:latest
          done
